# Generated by Django 3.1.13 on 2021-07-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('original', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expires', models.DateTimeField()),
            ],
        ),
    ]
