# Generated by Django 3.1.13 on 2021-07-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='original',
            field=models.URLField(max_length=1000),
        ),
    ]
